// Generated by CoffeeScript 1.6.2
var hide, show;

require('ember');

module.exports = Em.Mixin.create({
  didInsertElement: function() {
    this._super();
    return this.$().on('click', show.bind(this));
  }
});

hide = function(e) {
  var parentView;

  parentView = this.get('parentView');
  return parentView.destroy();
};

show = function(e) {
  var closeView, contentView, overlayView, parentView;

  Em.$('.component.overlay').remove();
  closeView = Em.View.create({
    template: Em.Handlebars.compile('✘'),
    classNames: ['close'],
    didInsertElement: function() {
      return this.$().on('click', hide.bind(this));
    }
  });
  contentView = this.get('overlay').create({
    classNames: ['content']
  });
  overlayView = Em.ContainerView.create({
    classNames: ['component', 'overlay'],
    childViews: ['closeView', 'contentView'],
    closeView: closeView,
    contentView: contentView
  });
  parentView = this.get('parentView');
  overlayView.append();
  return Em.run.next(function() {
    var el, left, offset, top, width;

    el = overlayView.$();
    width = el.width();
    offset = width / 2;
    left = e.pageX - offset;
    top = e.pageY;
    return el.css({
      top: "" + top + "px",
      left: "" + left + "px"
    });
  });
};
