// Generated by CoffeeScript 1.6.1
var get, set;

get = Em.get;

set = Em.set;

module.exports = Em.Mixin.create({
  click: function(e) {
    var closeView, contentView, overlayView, parentView;
    this._super();
    Em.$(".component.overlay").remove();
    closeView = Em.View.create({
      template: Em.Handlebars.compile("✘"),
      classNames: ["close"],
      click: function() {
        var parentView;
        parentView = get(this, "parentView");
        return parentView.destroy();
      }
    });
    contentView = get(this, "overlayViewClass").create({
      classNames: ["content"]
    });
    overlayView = Em.ContainerView.create({
      classNames: ["component", "overlay"],
      childViews: ["closeView", "contentView"],
      closeView: closeView,
      contentView: contentView
    });
    parentView = get(this, "parentView");
    overlayView.append();
    return Em.run.next(function() {
      var el, left, offset, top, width;
      el = overlayView.$();
      width = el.width();
      offset = width / 2;
      left = e.pageX - offset;
      top = e.pageY;
      return el.css({
        top: "" + top + "px",
        left: "" + left + "px"
      });
    });
  }
});
